name: ronasapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-191.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  scroll_bottom_navigation_bar: ^4.0.0
  intl: ^0.19.0
  infinite_carousel: ^1.0.3
  http: ^1.2.0
  provider: ^6.1.1
  flutter_card_swiper: ^7.0.0
  rive: ^0.12.4
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/movies/
    - assets/icons/
    - assets/rivassets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

    - family: Birds of Paradise 
      fonts:
        - asset: assets/fonts/Birds-of-Paradise.ttf
    - family: gangOfThree
      fonts:
        - asset: assets/fonts/go3v2.ttf
    - family: ToonyLine
      fonts:
        - asset: assets/fonts/ToonyLine.otf
    - family: VampireWars 
      fonts:
        - asset: assets/fonts/Vampire-Wars.ttf

